modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvySpecs"

[[mods]]
modId="envyspecs"
version="1.3.2"
displayName="EnvySpecs"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvySpecs
'''

[[dependencies.envyspecs]]
modId="forge"
mandatory=true
versionRange="[48.0.30,)"
ordering="NONE"
side="BOTH"

[[dependencies.envyspecs]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
